name: Build Cordova Android Release

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Cordova
      run: npm install -g cordova

    - name: Install npm dependencies
      run: npm install

    - name: Add Android platform
      run: cordova platform add android@13.0.0

    - name: Build Android Release
      run: |
        export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/emulator
        cordova build android --release

    - name: Upload AAB/APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: elvatv-release
        path: |
          platforms/android/app/build/outputs/bundle/release/app-release.aab
          platforms/android/app/build/outputs/apk/release/*.apk
